# Nixpacks build configuration for NexaGestion ERP
nixpacks:
  providers:
    - node

  variables:
    NODE_ENV: "production"
    NEXT_TELEMETRY_DISABLED: "1"

  # Use buildpacks phases instead of Dockerfile
  phases:
    setup:
      cmds:
        - apt-get update && apt-get install -y ca-certificates

    install:
      dependencyFile: package-lock.json
      dependencyFileCommand: npm ci

    build:
      cmds:
        - npm run build

    start:
      run: node .next/standalone/server.js
